#!/usr/bin/env python3

###Extracts the data from metadata csv and a seurat file to add to db

#load modules
import argparse
import subprocess
import mariadb
import mdb_helper_functions as helpers

#get args
parser = argparse.ArgumentParser()
parser.add_argument('meta_csv_path')
parser.add_argument('username')
parser.add_argument('password')
args = parser.parse_args()

#create queries
subprocess.call(['Rscript', 'MetaData_to_SQL.R', args.meta_csv_path])

#run queries
connection, cursor = helpers.connect_database(
      "bioed-new.bu.edu", 
      4253, 
      "Team10", 
      args.username,
      args.password
      ) #only username and password differ between runs

experiments = helpers.read_query_file("Fill_Experiments.sql") #names always the same
channels = helpers.read_query_file("Fill_Channels.sql") #generated by r script

#helpers.execute_query(cursor, experiments)
helpers.execute_query(cursor, channels)


#close out
cursor.close()
connection.close()
